name: CI

on:
  push:
    branches:
      - main
    
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: My_ERP
      DB_USERNAME: root
      DB_PASSWORD:     
    services:
      mysql-service:
        # Docker Hub image (also with version)
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: My_ERP
          MYSQL_ROOT_PASSWORD:          
        ports:
          - 3306
        # Set health checks to wait until mysql database has started (it takes some seconds to start)
        options: 
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer update --lock
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Execute tests
        run: php artisan test
